# this file must be UTF-8 encoded

package dynamicclassifier


# Use the standard page header
_header_ {_Style:header_}

# Dynamic classifier pages have the standard navigation bar and then what is generated by dynamicclassifieraction
_content_ {
_optnavigationbar_
}

# Use the standard page footer
_footer_ {_Style:footer_}
